# Generated by Django 4.1.2 on 2022-11-30 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('observation_name', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('value_type', models.CharField(blank=True, max_length=20, null=True)),
                ('value_units', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('monitored_id', models.CharField(max_length=200)),
                ('observation_name', models.CharField(max_length=200)),
                ('issued', models.DateTimeField()),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('value_type', models.CharField(blank=True, max_length=20, null=True)),
                ('value_units', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('components', models.ManyToManyField(blank=True, to='healthapi.components')),
            ],
        ),
    ]
