# Generated by Django 4.1.2 on 2022-11-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observation',
            new_name='Observations',
        ),
    ]
