# Generated by Django 4.1.2 on 2022-11-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapi', '0002_rename_observation_observations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Components',
            new_name='Component',
        ),
        migrations.RenameModel(
            old_name='Observations',
            new_name='Observation',
        ),
    ]
