# Generated by Django 4.1.3 on 2022-11-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapi', '0003_rename_components_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='components',
        ),
        migrations.AddField(
            model_name='component',
            name='observation_parent',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='healthapi.observation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='issued',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='monitored_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
