# Generated by Django 4.1.3 on 2022-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapi', '0004_remove_observation_components_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
