# Generated by Django 4.1.3 on 2022-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapi', '0005_alter_observation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='observation_name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='component',
            name='value_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='component',
            name='value_units',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='issued',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='monitored_id',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
