# Generated by Django 4.1.3 on 2022-11-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapi', '0006_alter_component_observation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='value_units',
            new_name='value_unit',
        ),
        migrations.AlterField(
            model_name='component',
            name='observation_name',
            field=models.CharField(max_length=200),
        ),
    ]
