# Generated by Django 4.1.3 on 2022-12-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapi', '0007_rename_value_units_component_value_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
